# Generated by Django 6.0.6 on 2026-07-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='boarding_status',
            field=models.CharField(choices=[('DAY', 'Day Scholar'), ('BOARDING', 'Boarding Scholar')], default='DAY', max_length=10),
        ),
    ]
