# Generated by Django 6.0.6 on 2026-08-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_boarding_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='former_school',
            field=models.CharField(blank=True, help_text='Previous school attended, if any.', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='nin',
            field=models.CharField(blank=True, help_text='National Identification Number, if the pupil has one.', max_length=50, verbose_name='NIN (optional)'),
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/'),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
