# Generated by Django 6.0.6 on 2026-08-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_former_school_student_nin_student_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('CATHOLIC', 'Catholic'), ('PROTESTANT', 'Protestant / Anglican'), ('MUSLIM', 'Muslim'), ('PENTECOSTAL', 'Pentecostal / Born Again'), ('SDA', 'Seventh-Day Adventist'), ('ORTHODOX', 'Orthodox'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
