# Generated by Django 6.0.6 on 2026-08-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nin',
            field=models.CharField(blank=True, help_text="National Identification Number of the pupil's guardian, if available.", max_length=50, verbose_name='Guardian NIN (optional)'),
        ),
    ]
