# Generated by Django 6.0.6 on 2026-08-05 19:25

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_nin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nin',
            field=models.CharField(blank=True, help_text='14 characters beginning with CM or CF, for example CM4900906P76ZE.', max_length=14, validators=[django.core.validators.RegexValidator(flags=re.RegexFlag['IGNORECASE'], message='Enter a valid 14-character Ugandan NIN beginning with CM or CF.', regex='^C[MF][A-Z0-9]{12}$')], verbose_name='Guardian NIN (optional)'),
        ),
    ]
