# Generated by Django 6.0.6 on 2026-07-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
        ('students', '0002_student_boarding_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='boarding_status',
            field=models.CharField(choices=[('DAY', 'Day Scholar'), ('BOARDING', 'Boarding Scholar')], default='DAY', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('school_class', 'term', 'year', 'boarding_status')},
        ),
    ]
